version: '3.9'

services:
  traefik:
    image: traefik:v3.0
    ports:
      - 80:80
      - 443:443
      - 23:23
      - 5001:5001
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "/mnt/media/traefik/letsencrypt:/letsencrypt"
    command:
      - --log.level=DEBUG
      - --accesslog=true
      - --providers.docker.network=web
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entryPoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.asDefault=true
      - --entrypoints.websecure.http.tls.certresolver=obresolver
      - --certificatesresolvers.obresolver.acme.email=bardic.knowledge@gmail.com
      - --certificatesresolvers.obresolver.acme.tlschallenge=true
      - --certificatesresolvers.obresolver.acme.storage=/letsencrypt/acme.json
  bitwarden:
    image: vaultwarden/server:1.30.1-alpine
    security_opt:
      - no-new-privileges:true
    networks:
      - web
    environment:
      - "SIGNUPS_ALLOWED=false"
    labels:
      - traefik.enable=true
      - traefik.http.routers.pass.rule=Host(`pass.openbracket.ca`)
      - traefik.http.services.pass.loadbalancer.server.port=80

      - traefik.http.middlewares.passredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.passredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.pass.middlewares=passredirect
    volumes:
      - /mnt/media/vaultwarden/data/:/data
  gotosocial:
    image: superseriousbusiness/gotosocial:latest
    container_name: gotosocial
    user: 1000:1000
    networks:
      - web
    environment:
      GTS_HOST: social.openbracket.ca
      GTS_DB_TYPE: sqlite
      GTS_DB_ADDRESS: /gotosocial/storage/sqlite.db
      GTS_LETSENCRYPT_ENABLED: "false"
      GTS_LETSENCRYPT_EMAIL_ADDRESS: ""
      TZ: America/Halifax

    volumes:
      - /mnt/media/gotosocial/data:/gotosocial/storage
    restart: "always"
    labels:
      - traefik.enable=true
      - traefik.http.routers.social.rule=Host(`social.openbracket.ca`)
      - traefik.http.services.social.loadbalancer.server.port=8080

      - traefik.http.middlewares.socialredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.socialredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.social.middlewares=socialredirect
networks:
  web:
    name: web
    external: true





    