version: '3.9'

services:
  traefik:
    image: traefik:v3.0
    ports:
      - 80:80
      - 443:443
      - 23:23
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "/media/traefik/letsencrypt:/letsencrypt"
    command:
      - --log.level=DEBUG
      - --accesslog=true
      - --providers.docker.network=web
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entryPoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.asDefault=true
      - --entrypoints.websecure.http.tls.certresolver=obresolver
      - --certificatesresolvers.obresolver.acme.email=bardic.knowledge@gmail.com
      - --certificatesresolvers.obresolver.acme.tlschallenge=true
      - --certificatesresolvers.obresolver.acme.storage=/letsencrypt/acme.json
  bitwarden:
    image: vaultwarden/server:1.30.1-alpine
    security_opt:
      - no-new-privileges:true
    networks:
      - web
    environment:
      - "SIGNUPS_ALLOWED=true"
    labels:
      - traefik.enable=true
      - traefik.http.routers.pass.rule=Host(`pass.openbracket.ca`)
      - traefik.http.services.pass.loadbalancer.server.port=80
      - traefik.http.middlewares.passredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.passredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.pass.middlewares=passredirect
    volumes:
      - /media/vaultwarden/data/:/data
  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 8080:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: https://openbracket.ca
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
    labels:
      - traefik.enable=true
      - traefik.http.routers.blog.rule=Host(`openbracket.ca`)
      - traefik.http.services.blog.loadbalancer.server.port=80
      - traefik.http.middlewares.blogredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.blogredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.blog.middlewares=blogredirect
    volumes:
      - ghost:/var/lib/ghost/content
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db:/var/lib/mysql

volumes:
  ghost:
  db:
networks:
  web:
    name: web