version: '3.9'

services:
  traefik:
    image: traefik:v3.0
    ports:
      - 80:80
      - 443:443
      - 23:23
      - 25:25
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "/media/traefik/letsencrypt:/letsencrypt"
    command:
      - --log.level=DEBUG
      - --accesslog=true
      - --providers.docker.network=web
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entryPoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.asDefault=true
      - --entrypoints.websecure.http.tls.certresolver=obresolver
      - --certificatesresolvers.obresolver.acme.email=bardic.knowledge@gmail.com
      - --certificatesresolvers.obresolver.acme.tlschallenge=true
      - --certificatesresolvers.obresolver.acme.storage=/letsencrypt/acme.json
  bitwarden:
    image: vaultwarden/server:1.30.1-alpine
    security_opt:
      - no-new-privileges:true
    networks:
      - web
    environment:
      - "SIGNUPS_ALLOWED=true"
    labels:
      - traefik.enable=true
      - traefik.http.routers.pass.rule=Host(`pass.openbracket.ca`)
      - traefik.http.services.pass.loadbalancer.server.port=80
      - traefik.http.middlewares.passredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.passredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.pass.middlewares=passredirect
    volumes:
      - /media/vaultwarden/data/:/data
  chasquid:
    image: registry.gitlab.com/albertito/chasquid:main
    networks:
      - web
    environment:
      - "AUTO_CERTS=mail.openbracket.ca"
    labels:
      - traefik.enable=true
      - traefik.http.routers.mail.rule=Host(`mail.openbracket.ca`)
      - traefik.http.services.mail.loadbalancer.server.port=25
      - traefik.http.middlewares.mailredirect.redirectregex.replacement=https://$${1}
      - traefik.http.middlewares.mailredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.routers.mail.middlewares=mailredirect
    volumes:
      - chasquid-data:/data
networks:
  web:
    name: web